<?php
return [
	'VERSION' => '5.0',
	'NAME' => 'BoaSoft.Top',
	'CHARSET' => 'UTF-8',
	'SALT' => 'boa2020',
	//'FILTER' => 'htmlspecialchars',
	//'DEBUG' => true,
	//'LANGUAGE' => 'zh-cn',
	//'VIEW_XML_ROOT' => 'boa',
	//'MSG_DISPLAY' => '',
	//'MSG_TYPE_VAR' => 'type',
	//'MSG_TYPE_VAL' => 'json',
	//'MSG_JSONP_CB' => 'message',
	//'MSG_STR_CLASS' => 'boa_msg',
	//'MSG_LOG_NOTICE' => false,
	//'ARCHIVE' => [],
	//'DATABASE' => [],
	//'COOKIE' => [],
	//'CACHE' => [],
	//'CRYPT' => [],
	//'SESSION' => [],
	//'HTTP' => [],
	//'MAIL' => [],
	//'DOWNLOAD' => [],
	//'UPLOAD' => [],
	//'ROUTER' => [],
	//'SECURITY' => [],
	//'FILE' => [],
	//'IMAGE' => [],
	//'JSON' => [],
	//'XML' => [],
	//'EVENT' => [],
	//'CONSOLE' => [],
	//'PAGE' => [],
	//'MQ' => [],
	//'LOG' => []
];
?>